using System;
using System.IO;


namespace SciSharp.Reporting.Matlab
{
    public class MatlabFile : Report
    {
        public void AddItem(MatlabElement element)
        {
            Elements.Add(element);
        }

        protected override void End(TextWriter output)
        {
            output.WriteLine("% --- End of file ---");
        }

        protected override void Begin(TextWriter output)
        {
            output.WriteLine("% Autogenerated file by ScientificTools (c) 2012");
            output.WriteLine("% Timestamp: {0}\n", DateTime.Now);
        }
    }
}
